version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "console-signin"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-gqx2hr6nxfoj"
s3_prefix = "console-signin"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

